### ISSUE TITLE
On clicking login I am presented with an error TemplateDoesNotExist at /auth/login

### ISSUE THREAD

**Issue by paul-fitzgibbons** [Santandersecurityresearch/asvs#64]
On clicking login I am presented with an error: TemplateDoesNotExist at /auth/login

Template-loader postmortem
Django tried loading these templates, in this order:

Using engine django:

django.template.loaders.filesystem.Loader: /app/templates/bootstrap3/uni_form.html (Source does not exist)
django.template.loaders.app_directories.Loader: /usr/lib/python3.10/site-packages/django/contrib/admin/templates/bootstrap3/uni_form.html (Source does not exist)
django.template.loaders.app_directories.Loader: /usr/lib/python3.10/site-packages/django/contrib/auth/templates/bootstrap3/uni_form.html (Source does not exist)
django.template.loaders.app_directories.Loader: /usr/lib/python3.10/site-packages/django_otp/templates/bootstrap3/uni_form.html (Source does not exist)
django.template.loaders.app_directories.Loader: /usr/lib/python3.10/site-packages/django_otp/plugins/otp_totp/templates/bootstrap3/uni_form.html (Source does not exist)

**Comment by aleHRevirtus** [comment]
Same problem to me!

**Comment by labiej** [comment]
This is caused by a breaking change in django-crispy-forms 2.0
They release template packs as standalone packages.

[https://github.com/django-crispy-forms/django-crispy-forms/issues/1336](An issue on the django-crispy-forms repository)

I'll open a PR later, for know it can be fixed by adding 2 lines

`crispy_bootstrap3` to  INSTALLED_APPS (asvs/settings.py)

and 

crispy-bootstrap3 to requirements.txt

**Comment by danielcuthbert** [comment]
thanks to @labiej for sorting the template issues, this is much appreciated!!

**Comment by danielcuthbert** [comment]
Confirmed fixed in latest release. Thank you all
